@baseUrl = http://localhost:3000/api

POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "username": "1111",
  "password":"1111"
}
###

POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
  "username": "1111",
  "password":"1111"
}
###


POST {{baseUrl}}/product/create
Content-Type: application/json

{
  "title": "hi",
  "description": "does this work?"
}
####

PATCH {{baseUrl}}/user/profile/6419d954b99a4b8a27d82fda
Content-Type: application/json

{
  "name": "Miguel Arias",
  "email": "argenis803@gmail.com"
}
